### ISSUE TITLE
Code gets crashed when i run ffmeg command

### ISSUE THREAD

**Issue by PuneetSalhotra** [chriswiggins/rtsp-streaming-server#11]
When i run command ffmpeg -i videoplayback.mp4  -c:v copy -f rtsp rtsp://test:test@127.0.0.1:6001/samplevideo then the main code gets crashed. Here is the error
UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Object.checkMount (/Users/puneet/Desktop/Project_Nodejs/rtsp-streaming-server/test/index.ts:36:15)
at module.exports.checkMount (/Users/puneet/Desktop/Project_Nodejs/rtsp-streaming-server/src/lib/PublishServer.ts:127:42)
I could not able to resolve it. let me know if there is any issue in command

ffplay -rtsp_flags listen rtsp://test:test@127.0.0.1:6002/samplevideo there is no file at this location

**Comment by chriswiggins** [comment]
Is there a reason you're doing a `-rtsp_flags listen` on your ffplay command? Try without this and see how you go

**Comment by chriswiggins** [comment]
Please re-open if you're still having issues
