### ISSUE TITLE
ETA: RTP interleaved in RTSP

### ISSUE THREAD

**Issue by ivocavalcante** [chriswiggins/rtsp-streaming-server#14]
Hi all,

Not really an issue, just an information. Do we have an ETA on RTP interleaved mode? Need this functionality for a project and I'm wondering if this tool could be used or I'd have to keep looking.

Thanks!

**Comment by chriswiggins** [comment]
Hey @ivocavalcante, I don't really have time to work on that at the moment sorry - other work is taking priority. I do see there are other libraries that support it, so I do hope there is something there that you can use.
