### ISSUE TITLE
Pipe data to FFMPEG or other command?

### ISSUE THREAD

**Issue by mattwa1sh** [chriswiggins/rtsp-streaming-server#2]
Hi--

Is there a way I can  accept an RTSP connection and then pipe the data to another ffmpeg command so I can push out to my CDN as HLS? (Rather than viewing the inputted RTSP?)

Thanks!
Matt

**Comment by chriswiggins** [comment]
Not directly - you could use the new hook functionality to listen for a published stream and then fire up a process to push to a CDN if you wish.

(Closing old issues out)
