### ISSUE TITLE
DESCRIBE is not implemented

### ISSUE THREAD

**Issue by megupta** [chriswiggins/rtsp-streaming-server#8]
The method DESCRIBE is not implemented. It is required as per spec: https://tools.ietf.org/html/rfc2326#page-31

Attempted to retrieve stream as per docs:
ffmpeg -i rtsp://127.0.0.1:5554/stream1

Errors:
Unknown PublishServer request { method: 'DESCRIBE', url: undefined }

**Comment by chriswiggins** [comment]
Apologies @megupta, the docs are wrong (I’ll update soon)

Please use the client port 6554 instead
