### ISSUE TITLE
Unknown PublishServer request 'DESCRIBE', 'PLAY'

### ISSUE THREAD

**Issue by bingbing720** [chriswiggins/rtsp-streaming-server#9]
Hello.
I have implemented simple rtsp server based on your library.
I am getting error 'unknown PlublishServer request 'DESCRIBE' and 'PLAY'.
 
![image](https://user-images.githubusercontent.com/19614418/60517174-cbc1ee80-9d11-11e9-85f9-c0fbb8633053.png)
'DESCRIBE' and 'PLAY' are standard protocol directives but are they not implemented yet?
if so rtsp server is working properly?

**Comment by chriswiggins** [comment]
Hi @bingbing720 - you need to PUBLISH streams on the `PublishServer` port, and then PLAY streams on the `ClientServer` port . Can you show your `rtsp.js` file?

**Comment by bingbing720** [comment]
It's totally same with sample code. 
I don't know how to implement two features and also couldn't any document about them.
Would you share some code ?
Thank you.

const RtspServer = require('rtsp-streaming-server').default

const server = new RtspServer({
serverPort: 7004,
clientPort: 8004,
rtpPortStart: 10000,
rtpPortCount: 10000
});

async function run () {
try {
await server.start();
} catch (e) {
console.error(e);
}
}

run();

**Comment by chriswiggins** [comment]
So first of all, you need to send a stream into the RTSP server using an application that supports RTSP ANNOUNCE (like ffmpeg):

`ffmpeg -re -i video.mp4 -c:v copy -f rtsp rtsp://127.0.0.1:7004/stream1`

And then you can watch your stream:

`ffplay rtsp://127.0.0.1:8004/stream1`

**Comment by bingbing720** [comment]
Thank you.
I did it. and then when I tried to play rtsp url using vlc player the above issue happened.

**Comment by chriswiggins** [comment]
What RTSP url did you use in VLC?

**Comment by bingbing720** [comment]
it's some snippet of python code.
....
command = ['ffmpeg',
        '-f', 'rawvideo',
        '-pix_fmt','bgr24',
        '-s', cam_res,
        '-r', str(cam_fps),
        '-i', '-',
	'-f', 'rtsp', 'rtsp://172.16.1.22:7004/cam1',
	#'http://localhost:8090/feed1.ffm'
	#'-f', 'mpegts', 'output.mp4'
	]
proc = sp.Popen(command, stdin=sp.PIPE)
......
proc.stdin.write(frame.tobytes())

After it I opened 'rtsp://172.16.1.22:7004/cam1' through as VLC player network stream.

**Comment by chriswiggins** [comment]
You're using the wrong RTSP port in VLC. Note that there is a port to **publish** and a port to **play**

Open `rtsp://172.16.1.22:8004/cam1` in VLC (note the 8004 port)

**Comment by bingbing720** [comment]
It's working now.
Appreciate your help.
Thank you so much.

**Comment by chriswiggins** [comment]
You’re welcome! I realised the documentation was wrong too
